apiVersion: v1
kind: Namespace
metadata:
  name: sleyton

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: sleyton
data:
  USERNAME: "seba"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: sleyton
type: Opaque
data:
  # echo -n 'my-super-api-key' | base64
  API_KEY: bXktc3VwZXItYXBpLWtleQ==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-test
  namespace: sleyton
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-test
  template:
    metadata:
      labels:
        app: backend-test
    spec:
      containers:
        - name: backend
          image: sleytonduoc/backend-test:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: USERNAME
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: API_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: sleyton
spec:
  type: ClusterIP
  selector:
    app: backend-test
  ports:
    - port: 80
      targetPort: 4000
